FROM ruby:2.7.0-slim

RUN apt-get update -qq && apt-get -y install build-essential nodejs sqlite3 libsqlite3-dev

WORKDIR /usr/src/myapp

COPY Gemfile* ./

RUN gem install bundler:2.0.0.pre.3 && bundle _2.0.0.pre.3_ install

COPY ./ ./

RUN bundle exec rake db:migrate RAILS_ENV=test

CMD [ "bundle", "exec", "cucumber", "features/search_movie.feature" ]
# CMD [ "/bin/sh", "-c", "sh" ]